apiVersion: v2
version: 1.0.0
name: echo-server
dependencies:
  - name: echo-server
    version: 0.5.0
    repository: https://ealenn.github.io/charts
  - name: podinfo
    version: "6.11.1"
    repository: https://stefanprodan.github.io/podinfo
  - name: podinfo
    alias: podinfotest
    version: "6.11.1"
    repository: https://stefanprodan.github.io/podinfo
